Bowen
LinhTangTD/SIR_Modeling pull request #14
Opened 2020-12-13 22:35 UTC by minceb

2020-12-13 22:45 UTC, LinhTangTD requested changes
Just add some notes, I think generally the code looks awesome! Thank you!

2020-12-13 22:45 UTC, LinhTangTD commented on SIHRDmodel with variability.Rmd
> +    Recovered.Hospital.today <- rbinom(1, Leaving.Hospital, theta)
Can you change <- to = just for consistency? Sorry for being nit-pick but it is also easier to detect on Github lol

2020-12-13 22:45 UTC, LinhTangTD commented on SIHRDmodel with variability.Rmd
> +  # Watch the disease until it ends (daily new case = 0) or at max 200 days
I'm not sure how to define the "end" of the disease, should we do daily new case = 0 or infected = 0?

2020-12-13 22:45 UTC, LinhTangTD commented on SIHRDmodel with variability.Rmd
> +
Is this a duplicate by mistake or is there anything changed in the previous experiment? (line 150-288)

2020-12-14 04:30 UTC, britneyhe approved these changes

2020-12-14 04:30 UTC, merged